// <auto-generated />
using System;
using API_PEDAJE_V2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_PEDAJE_V2.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20240620234427_pedaje")]
    partial class pedaje
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_PEDAJE_V2.Models.Peaje", b =>
                {
                    b.Property<int>("idPeaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idPeaje"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateOnly?>("fechaRegistro")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("idCategoria")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("peaje")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("placa")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<decimal?>("precio")
                        .IsRequired()
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idPeaje");

                    b.ToTable("peaje");
                });
#pragma warning restore 612, 618
        }
    }
}
